
# =====================================================
# Data displayed on the Home (About Me) page.
#
# üí° Tip for Images / Logo:
# You can use either:
# 1. A full URL (e.g., https://example.com/logo.png)
# 2. A local file placed under /public/images/ and referenced with "/" (e.g., "/images/logo.png")
# =====================================================

# =====================================================
# üë§ Personal Information
# =====================================================

profile:
  name: "Chayanth"
  headline: "Student @ Toronto Metropolitan University"
  email: "chayanthsuthahar@gmail.com"
  location: null
  profileImage: "/images/Headshot.jpg"

  links:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/chayanth/"
      icon:
        name: "FaLinkedin"
        package: "react-icons/fa6"


    - name: "R√©sum√©"
      url: "/pdf/sample-resume.pdf"
      icon:
        name: "FaRegIdBadge"
        package: "react-icons/fa6"

    - name: "Github"
      url: "https://github.com/[your-github]"
      icon:
        name: "FaGithub"
        package: "react-icons/fa6"

  # you can use HTML syntax here (e.g. <br/>, <a>, <strong>, ...)
  biography: |
    Hi! I'm <strong>Chayanth</strong>, a <em>mechanical engineering</em> passionate about <em>robotics</em>. Currently, I study as a <em>Mechanical engineer</em> at <em>Toronto Metropolitan University </em> with a passion for hands-on design, mechanical systems, and collaborative problem-solving.</em>. 
    With a background in <em> FRC team 2056</em>, I've developed <em> experience in CAD modeling, fabrication, and rapid prototyping, with tools including SolidWorks.
    <div class="my-2"></div>
    Outside of work, I enjoy participating in hackathons, robotics competitions, and design challenges that push both my technical skills and creativity. Thanks for visiting feel free to <a href="mailto:chayanthsuthahar@gmail.com" target="_blank" rel="noopener noreferrer">reach out</a> to connect.
# # =====================================================
# # üéì Education Section
# # =====================================================

education:
  - degree: "BEng in Mechanical engineering"
    school: "Toronto Metropolitan University"
    years: "2025 - Present"
    logo: "https://www.torontomu.ca/content/dam/calendar/images/TMU-Shield-WATERMARK1.jpg"

  - degree: " Ontario Secondary School Diploma (OSSD)"
    school: "Orchard Park Secondary School"
    years: "2021 - 2025"
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5TCC2jBMkC4TVAckyChCd5o_04c88cOZsqw&s"


# # =====================================================
# # üíº Work Experience Section
# # =====================================================

workExperience:
  - title: "Strategy Representative and Design Member"
    company: "2056"
    years: "2021 - 2025"
    logo: "http://thebluealliance.com/avatar/2026/frc2056.png"

  - title: "Operations Team Member"
    company: "Hammer Hacks"
    years: "Jul 2023 - Nov 2024"
    logo: "/images/HammerHacks.jpg"

  - title: "Board of Directors"
    company: "Stoney Creek Student Council"
    years: "Sept 2022- Jun 2025"
    logo: "/images/youthCouncil.jpg"

# # =====================================================
# # üé§ Presentations / Talks Section
# # =====================================================

talks:
  - category: "Misc"
    title: "[Your Talk Title Here]"
    organization: "[Your Talk Location Here]"
    date: "[Month Day, Year]"
    link: "https://example.com/your-talk-link"
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Example_image.svg"

  - category: "Workshop"
    title: "Deep Learning with Keras"
    organization: "University of Illinois Urbana-Champaign (UIUC)"
    date: "Sep 4, 2019"
    link: null
    image: "https://pm25.github.io/images/uiuc-workshop.webp"

  - category: "Workshop"
    title: "Practical Guide to PyTorch"
    organization: "ABC University"
    date: "Dec 5, 2022"
    link: "https://example.com/workshop-talk"
    image: null

# # =====================================================
# # üõ°Ô∏è Professional Services
# # =====================================================

services:
  - category: "Misc"
    role: "[Role]"
    organization: "[Organization]"
    date: "[Year]"
    link: "https://example.com/workshop-talk"
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Example_image.svg"

  - category: "Research"
    role: "Reviewer"
    organization: "TPAMI 2024, NeurIPS 2025"
    date: "2024-2025"
    link: null
    image: null

  - category: "Research"
    role: "Program Committee Member"
    organization: "CVPR 2022"
    date: "2022"
    link: null
    image: null

  - category: "Teaching"
    role: "Teaching Assistant"
    organization: "National Taiwan University - Data Structures & Algorithms"
    date: "2021"
    link: null
    image: null

# # =====================================================
# # üõ†Ô∏è Skills Section
# # =====================================================

skills:
  CAD:
    - name: "SolidWorks"
      logo: "https://upload.wikimedia.org/wikipedia/commons/f/f7/SolidWorks_Logo.svg"
      proficiency: Advanced
      description: "Designed 10+ major robot components for FRC Team 2056."
    - name: "Onshape"
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Onshape_logo.png/320px-Onshape_logo.png"
      proficiency: Fluent
      description: null
    - name: "AutoCAD"
      logo: "https://upload.wikimedia.org/wikipedia/commons/7/7d/AutoCAD_2023.svg"
      proficiency: Fluent
      description: null

  Fabrication:
    - name: "CNC Machining"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/OOjs_UI_icon_academic-progressive.svg"
      proficiency: Experienced
      description: null
    - name: "Milling & Lathe"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/OOjs_UI_icon_academic-progressive.svg"
      proficiency: Experienced
      description: null
    - name: "Soldering"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/OOjs_UI_icon_academic-progressive.svg"
      proficiency: Experienced
      description: null

  Projects:
    - name: "FRC Robotics"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/OOjs_UI_icon_academic-progressive.svg"
      proficiency: "2022 - 2025"
      description: "Ontario District Champions & FRC World Championships 1st place (2025) with Team 2056."
    - name: "Keep'on Cooking"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/OOjs_UI_icon_academic-progressive.svg"
      proficiency: "2024"
      description: "Pomodoro productivity device built at McMaster Designathon."

  Language:
    - name: "English"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/OOjs_UI_icon_language-ltr-progressive.svg"
      proficiency: Fluent
      description: "Professional working proficiency."
